# We need sudo so we can install dependencies
sudo: required
dist: trusty

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

# Install necessary dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y autoconf automake pkg-config intltool libglib2.0-dev xsltproc docbook-xsl docbook-xml iptables ipset ebtables python-slip-dbus libxml2-utils realpath

# nftables is not available in Ubuntu Trusty, but supported in the kernel.
# Once travis supports a newer Ubuntu version we can remove this and add
# nftables to the apt comamnd above.
install:
  - sudo apt-get -qq -y install libmnl-dev libgmp-dev libreadline-dev
    && pushd /tmp
    && wget ftp://ftp.netfilter.org/pub/libnftnl/libnftnl-1.0.9.tar.bz2
    && tar xf libnftnl-1.0.9.tar.bz2
    && cd libnftnl-1.0.9
    && ./configure
    && make
    && sudo make install
    && cd /tmp
    && wget ftp://ftp.netfilter.org/pub/nftables/nftables-0.8.2.tar.bz2
    && tar xf nftables-0.8.2.tar.bz2
    && cd nftables-0.8.2
    && ./configure --disable-man-doc
    && make
    && sudo make install
    && popd

script:
  # Do a parallel build to spot potential dependency problems.
  # No ebtables-restore in ubuntu 14.04
  - ./autogen.sh --with-ebtables-restore=/bin/false --sysconfdir=/etc && make -j32
  - ./config/xmlschema/check.sh -d $(pwd)/config
  # run the tests suite, must install some policy first
  - sudo make -C config install-dist_dbus_policyDATA install-polkit1_actionDATA
  - sudo ln -sf /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.server.policy
                /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.policy
  - sudo pkill -HUP dbus-daemon || true
  - sudo pkill -HUP polkitd || true
  - sudo make check || { cat src/tests/testsuite.log; exit 1; }

# uncomment to add IRC notifications
# 
#notifications:
#  irc: "chat.freenode.net#firewalld"
#    use_notice: true
